apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reaktor-web
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: overlay/production
    repoURL: https://github.com/ThangEthan/reaktor-web-conf.git
    targetRevision: HEAD
    kustomize: 
      version: v4.4.0 
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
